language: python
python:
    - "2.7"
services:
    - postgresql
env:
    -DJANGO=1.11.3 DB=postgresql
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install psycopg2 --quiet
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
# command to run tests
script:
    - python manage.py test # or py.test for Python versions 3.5 and below