# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 06:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('rating', models.FloatField(null=True)),
                ('website', models.URLField(null=True)),
                ('maps_url', models.URLField(null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
