# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeyourfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=b''), size=None),
        ),
    ]
