# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeyourfood', '0003_auto_20171125_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='distance_from_route',
            field=models.FloatField(default=None),
        ),
    ]
