# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeyourfood', '0004_restaurant_distance_from_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
